### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by itabashitatsuro** [itabashitatsuro/chat-space#9]
＃IPアドレス
18.178.185.217

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう
②サイドバーの下線を消しましょう
③ヘッダーのグループ名が、カリキュラムの指定通りに表示されるようにしましょう
④Editボタンの下線を消し、文字色をカリキュラムの指定通りにしましょう**

[修正箇所の画像]
①
<img width="1431" alt="自動更新" src="https://user-images.githubusercontent.com/49669977/86735269-a460d880-c06d-11ea-8d43-cd6cc5ffc509.png">


②〜④
<img width="591" alt="スクリーンショット 2020-07-07 16 17 58" src="https://user-images.githubusercontent.com/49669977/86735321-afb40400-c06d-11ea-98f1-98385f5fd3fe.png">



[修正箇所の見本画像]
③、④
![スクリーンショット 2020-06-24 16 52 55](https://user-images.githubusercontent.com/49669977/86735453-c9554b80-c06d-11ea-9a02-389f84459eff.png)


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by itabashitatsuro** [comment]
先ほど、フォームの提出をいたしました。
確認をお願いします。

**Comment by mutorisa** [comment]
ご提出ありがとうございます！！
再度挙動確認させて頂いたところ、
**前回ご指摘させていただいた事項の修正確認ができませんでした。**
今一度本番環境で問題なく反映されているかご確認をお願いします。

**[現在もこのように表示されています]**
<img width="852" alt="スクリーンショット 2020-07-07 18 50 40" src="https://user-images.githubusercontent.com/65144927/86764284-e47e8600-c082-11ea-82af-aad29d545f90.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by itabashitatsuro** [comment]
先ほどは大変申し訳ありませんでした。
デプロイの作業がうまくいっておりませんでした。
もう一度、確認をお願いします。

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！！
挙動確認させて頂いたところ、②③④については修正の確認できました✨
ただし、**①グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう**
については修正の確認ができませんでした。
今一度ご確認をお願いします

**[参考]**
https://master.tech-camp.in/curriculums/4278

修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただきご提出をお願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by itabashitatsuro** [comment]
昨日からたびたび申し訳ございません。
上記①の修正をいたしました。
確認をお願い致します。

**Comment by mutorisa** [comment]
修正後、再度ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

⭐️今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
